version: '3'

services:
  mariadb:
    container_name: mariadb_tmss_auth
    image: bitnami/mariadb:10.7.8-debian-11-r6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_ROOT_USER=${DB_USERNAME}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 3301:3306
    volumes:
      - probox_volume:/bitnami/mariadb
    #networks:
      #tmpss_auth_net:
        #aliases:
          #- api.local

  bitnami:
    container_name: bitnami_tmss_auth
    image: bitnami/laravel:7.0.0-debian-10-r7
    working_dir: /app
    volumes:
      - /mnt/c/software/probox_laravel:/app
    ports:
      #- "0.0.0.0:8001:8001" 
      #- ":::8001:8001"
      - 8090:8090
    #extra_hosts:
      #- dockerhost.localhost:172.17.0.1
      #- 'host.docker.internal:host-gateway'  
    environment:
      - DB_HOST=mariadb
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}     
    command: >
      sh -c "composer install && composer update && npm run start"  
    depends_on:
      - mariadb    
    #networks:
      #tmpss_auth_net:
        #aliases:
          #- api.local

  phpmyadmin:
    image: bitnami/phpmyadmin:5.2.1-debian-12-r33
    ports:
      - '8081:8080'
      - '443:8443'
    depends_on:
      - mariadb
      
volumes:
  probox_volume:
    external: true

#networks:
  #tmpss_auth_net:
    #external: true
    #name: tmpss_auth_net